from typing import Optional

PHRASES = {
    "babyfood": "хүүхдийн хоол",
    "all-purpose flour": "ерөнхий зориулалтын гурил",
    "baking powder": "хөөлгөгч нунтаг",
    "blood glucose": "цусан дахь глюкоз",
    "brown rice": "бор будаа",
    "butter oil": "цөцгийн тосны тос",
    "cream cheese": "крем бяслаг",
    "egg white": "өндөгний цагаан",
    "egg yolk": "өндөгний шар",
    "ice cream": "зайрмаг",
    "low fat": "өөх тос багатай",
    "olive oil": "оливын тос",
    "peanut flour": "газрын самрын гурил",
    "powdered sugar": "нунтаг сахар",
    "sour cream": "зөөхий",
    "soy milk": "шар буурцгийн сүү",
    "white rice": "цагаан будаа",
    "whole wheat": "бүхэл үрийн улаан буудай",
}

STOP_WORDS = {
    "a", "about", "added", "all", "and", "as", "by", "campbell", "commercially",
    "composite", "equal", "foods", "for", "from", "grades", "in", "includes",
    "kellogg", "keebler", "made", "new", "of", "off", "on", "only", "or",
    "original", "products", "quaker", "ready", "recipe", "restaurant", "serve",
    "style", "to", "type", "usda", "variety", "volume", "with",
}

WORDS = {
    "almond": "бүйлс",
    "arm": "мөр",
    "apple": "алим",
    "australian": "австрали",
    "baked": "жигнэсэн",
    "barley": "арвай",
    "beans": "шош",
    "beef": "үхрийн мах",
    "beverages": "ундаа",
    "blade": "дал",
    "boiled": "чанасан",
    "boneless": "ясгүй",
    "bottom": "доод",
    "braised": "жигнэж болгосон",
    "breading": "бүрмэл",
    "breast": "цээж",
    "brisket": "өвчүү",
    "bread": "талх",
    "broiled": "шарах шүүгээнд болгосон",
    "broilers": "тахиа",
    "brown": "бор",
    "broth": "шөл",
    "butter": "цөцгийн тос",
    "buttermilk": "айраглаг сүү",
    "cabbage": "байцаа",
    "cake": "кекс",
    "cakes": "кекс",
    "calf": "тугал",
    "canned": "лаазалсан",
    "candies": "чихэр",
    "candy": "чихэр",
    "carrot": "лууван",
    "center": "голын",
    "cereal": "өглөөний хоол",
    "cereals": "өглөөний хоол",
    "cheese": "бяслаг",
    "chicken": "тахиа",
    "chip": "чипс",
    "chips": "чипс",
    "choice": "сонгомол",
    "chocolate": "шоколад",
    "chops": "хавирганы мах",
    "chuck": "далны мах",
    "chunky": "бүхэл хэсэгтэй",
    "coconut": "кокос",
    "cookie": "жигнэмэг",
    "cookies": "жигнэмэг",
    "cooked": "болгосон",
    "corn": "эрдэнэ шиш",
    "country": "хөдөөний",
    "crackers": "жигнэмэг",
    "creme": "крем",
    "cream": "крем",
    "crust": "зах",
    "cured": "даршилсан",
    "cut": "хэрчим",
    "cuts": "хэрчим",
    "dark": "бараан",
    "dinner": "оройн хоол",
    "domestic": "дотоодын",
    "drained": "шүүсэн",
    "drink": "ундаа",
    "drumstick": "мөч",
    "dry": "хуурай",
    "egg": "өндөг",
    "end": "төгсгөл",
    "enriched": "баяжуулсан",
    "fat": "өөх тос",
    "fast": "түргэн",
    "fish": "загас",
    "flavor": "амттай",
    "flour": "гурил",
    "fortified": "баяжуулсан",
    "fresh": "шинэ",
    "french": "франц",
    "fried": "шарсан",
    "frozen": "хөлдөөсөн",
    "fruit": "жимс",
    "fryers": "тахиа",
    "fudge": "карамель",
    "garlic": "сармис",
    "gluten": "цавуулаг",
    "grain": "үр тариа",
    "grilled": "гриллдсэн",
    "ground": "татсан",
    "half": "тал",
    "ham": "гахайн утсан мах",
    "heated": "халаасан",
    "home": "гэрийн",
    "imported": "импортын",
    "industrial": "үйлдвэрийн",
    "instant": "түргэн",
    "italian": "итали",
    "lamb": "хонины мах",
    "lean": "өөх багатай",
    "leg": "гуя",
    "lemon": "нимбэг",
    "lettuce": "шанцай",
    "light": "цайвар",
    "loin": "нурууны мах",
    "margarine": "маргарин",
    "mature": "боловсорсон",
    "meat": "мах",
    "meats": "мах",
    "milk": "сүү",
    "mix": "холимог",
    "mutton": "хонины мах",
    "natural": "байгалийн",
    "no": "байхгүй",
    "nonfat": "өөх тосгүй",
    "noodle": "гоймон",
    "noodles": "гоймон",
    "nuts": "самар",
    "oat": "овъёос",
    "oatmeal": "овъёосны каш",
    "oil": "тос",
    "onion": "сонгино",
    "pan": "хайруулын",
    "pasta": "паста",
    "patty": "котлет",
    "peanut": "газрын самар",
    "pizza": "пицца",
    "plain": "энгийн",
    "pork": "гахайн мах",
    "pot": "тогоонд болгосон",
    "potato": "төмс",
    "potatoes": "төмс",
    "prepared": "бэлтгэсэн",
    "protein": "уураг",
    "raw": "түүхий",
    "red": "улаан",
    "reduced": "багасгасан",
    "regular": "энгийн",
    "retail": "жижиглэн",
    "rib": "хавирга",
    "ribs": "хавирга",
    "rice": "будаа",
    "roast": "шарсан мах",
    "roasted": "шарсан",
    "round": "гуяны мах",
    "rye": "хөх тарианы",
    "salad": "салат",
    "sandwich": "сэндвич",
    "sauce": "соус",
    "sausage": "хиам",
    "seeds": "үр",
    "select": "сонгомол",
    "separable": "салгаж болох",
    "shank": "шаант",
    "short": "богино",
    "shoulder": "мөрний мах",
    "sirloin": "нурууны мах",
    "skin": "арьс",
    "small": "жижиг",
    "sodium": "натри",
    "soft": "зөөлөн",
    "solution": "уусмал",
    "salt": "давс",
    "snack": "зууш",
    "snacks": "зууш",
    "soup": "шөл",
    "soups": "шөл",
    "soy": "шар буурцаг",
    "spread": "түрхлэг",
    "steak": "стейк",
    "stewed": "жигнэсэн",
    "strained": "шүүсэн",
    "sugar": "сахар",
    "sweet": "чихэрлэг",
    "tea": "цай",
    "tenderloin": "зөөлөн нурууны мах",
    "tip": "үзүүр",
    "tomato": "улаан лооль",
    "top": "дээд",
    "toasted": "шарсан",
    "trimmed": "цэвэрлэсэн",
    "turkey": "цацагт хяруул",
    "unenriched": "баяжуулаагүй",
    "unheated": "халаагаагүй",
    "unprepared": "бэлтгээгүй",
    "vanilla": "ваниль",
    "vegetable": "ногооны",
    "vegetables": "ногоо",
    "vitamin": "витамин",
    "water": "ус",
    "wheat": "улаан буудайн",
    "white": "цагаан",
    "yogurt": "тараг",
    "yolk": "шар",
    "zealand": "зеланд",
}


def _translate_part(part: str) -> str:
    text = part.strip().lower()
    if not text:
        return ""
    if text in PHRASES:
        return PHRASES[text]

    for phrase, translated in sorted(PHRASES.items(), key=lambda item: len(item[0]), reverse=True):
        text = text.replace(phrase, translated)

    words = []
    for token in text.replace("-", " ").replace("/", " ").split():
        clean = token.strip("()[]{}.,")
        if clean in STOP_WORDS:
            continue
        translated = WORDS.get(clean)
        if translated:
            words.append(translated)
    return " ".join(words).strip()


def display_food_name(name: str, name_mn: Optional[str] = None) -> str:
    if name_mn and str(name_mn).strip():
        return str(name_mn).strip()

    parts = [_translate_part(part) for part in str(name).split(",")]
    parts = [part for part in parts if part]
    if not parts:
        return "Хүнсний бүтээгдэхүүн"

    # USDA-style names are often "Flour, rye, light". For common noun + modifiers,
    # putting modifiers before the noun reads more naturally in Mongolian.
    if parts[0] in {"гурил", "будаа", "талх", "гоймон", "мах", "сүү", "тос"} and len(parts) > 1:
        return f"{' '.join(parts[1:])} {parts[0]}"
    return ", ".join(parts)
